"""Write down which birds have no plate, and why they have none.

    python -m scripts.missing_plates            # regenerate the tracked file
    python -m scripts.missing_plates --check    # fail if it is out of date

The corpus the builder searches -- at the time of writing, Keulemans on
Commons -- does not cover everything, and some of what it does cover was
looked at and refused. Both leave the same hole on the board: the species
falls back to a Wikimedia photograph, which on six inks is the weaker
picture. Knowing which birds those are is what makes the hole fixable --
somebody can go and find a plate for the carrion crow, and widening which
artists or works count is one of the ways that could happen.

The list is generated rather than written by hand, because a hand-written
one is wrong the moment the next batch runs. `--check` exits non-zero when
the tracked file no longer matches the database, which is the form CI wants.

Three kinds of gap, kept apart because they need different work:

    searched, nothing found    nothing usable in the corpus as it stands;
                               widen the corpus or find an image elsewhere
    excluded on judgement      a plate was found and we said no; the reason
                               is carried through from plate_exclusions
    not yet searched           run the builder for those ranks

Rank is how often the species is actually reported in the region, so the
gaps are not equal: the board asks for its headline bird's plate every time
that bird leads, and rank 6 leads far more often than rank 98 does.
"""

from __future__ import annotations

import argparse
import json
import logging
import sqlite3
import sys
from pathlib import Path
from typing import Any, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from birddisplay.log import setup_logging  # noqa: E402

log = logging.getLogger("missing_plates")

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPECIES = REPO_ROOT / "data" / "uk_birds_top200.json"
DEFAULT_EXCLUSIONS = REPO_ROOT / "data" / "plate_exclusions.json"
DEFAULT_DB = REPO_ROOT / "assets" / "plates" / "keulemans_uk.sqlite"
DEFAULT_OUT = REPO_ROOT / "data" / "missing_plates.json"

# The builder is run in blocks (--skip 100 --limit 50), so the block holding
# the highest-ranked plate is the last block that was searched.
BATCH = 50

# Gaps at or above this rank are the expensive ones: common birds the board
# will want as its headline often. Listed twice on purpose -- once up top
# where they cannot be missed, once in their own section.
COMMON_ENOUGH_TO_HURT = 60

DESCRIPTION = (
    "Birds in data/uk_birds_top200.json with no plate in the plate"
    " database, generated by scripts/missing_plates.py -- run it again"
    " after every build rather than editing this file. Rank is how often"
    " the species is reported here, so the gaps cost different amounts:"
    " when a bird with no plate is the headline, the board falls back to a"
    " Wikimedia photograph, and a bird at rank 6 leads the board far more"
    " often than one at rank 98. `searched_no_plate` means the builder"
    " looked and found nothing usable in the corpus it currently searches,"
    " which is a corpus that can be widened; `excluded` means a plate was"
    " found, looked at and refused, with the reason carried through from"
    " data/plate_exclusions.json; `not_yet_searched` are ranks the builder"
    " has not reached, which is not the same as missing."
)


def load_species(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = data["species"] if isinstance(data, dict) else data
    return sorted(rows, key=lambda row: int(row["rank"]))


def plate_ranks(path: Path) -> set[int]:
    """The ranks that have a plate. An unreadable database means no plates."""
    if not path.exists():
        log.warning("no plate database at %s; treating every rank as missing", path)
        return set()
    connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    try:
        rows = connection.execute("SELECT rank FROM plates").fetchall()
    except sqlite3.Error as exc:
        log.warning("could not read %s: %s", path, exc)
        return set()
    finally:
        connection.close()
    return {int(row[0]) for row in rows}


def refusals(path: Path) -> dict[str, list[dict[str, str]]]:
    """What a human refused, keyed by common name.

    A file and a whole work are different refusals but the same answer to
    "why is this bird missing", so they come back in one list.
    """
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, list[dict[str, str]]] = {}
    for row in data.get("excluded", []):
        out.setdefault(row["species"], []).append(
            {"file": row["file"], "reason": row["reason"]}
        )
    for row in data.get("excluded_works", []):
        out.setdefault(row["species"], []).append(
            {"work": row["work"], "reason": row["reason"]}
        )
    return out


def _entry(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "rank": int(row["rank"]),
        "common_name": row["common_name"],
        "scientific_name": row["scientific_name"],
    }


def searched_through(ranks: set[int], species: Sequence[dict[str, Any]]) -> int:
    """How far down the list the builder has got.

    Inferred from the highest rank that has a plate, rounded up to the end
    of its block: a build of ranks 101-150 that found nothing after 149
    still searched 150. Override it with --searched-through when a whole
    block came back empty, which no block has yet.
    """
    if not ranks:
        return 0
    last = max(ranks)
    return min(((last + BATCH - 1) // BATCH) * BATCH, len(species))


def build(
    species: Sequence[dict[str, Any]],
    ranks: set[int],
    refused: dict[str, list[dict[str, str]]],
    through: int,
) -> dict[str, Any]:
    searched_gaps: list[dict[str, Any]] = []
    excluded: list[dict[str, Any]] = []
    not_searched: list[dict[str, Any]] = []

    for row in species:
        rank = int(row["rank"])
        if rank in ranks:
            continue
        if rank > through:
            not_searched.append(_entry(row))
        elif row["common_name"] in refused:
            excluded.append({**_entry(row), "refused": refused[row["common_name"]]})
        else:
            searched_gaps.append(_entry(row))

    gaps = sorted(searched_gaps + excluded, key=lambda row: row["rank"])
    return {
        "description": DESCRIPTION,
        "searched_through_rank": through,
        "counts": {
            "species": len(species),
            "with_plate": len(ranks),
            "searched_no_plate": len(searched_gaps),
            "excluded": len(excluded),
            "not_yet_searched": len(not_searched),
        },
        "commonest_gaps": [
            {"rank": row["rank"], "common_name": row["common_name"]}
            for row in gaps
            if row["rank"] <= COMMON_ENOUGH_TO_HURT
        ],
        "searched_no_plate": searched_gaps,
        "excluded": excluded,
        "not_yet_searched": not_searched,
    }


def render(report: dict[str, Any]) -> str:
    return json.dumps(report, indent=1, ensure_ascii=False) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--species", type=Path, default=DEFAULT_SPECIES)
    parser.add_argument("--plates", type=Path, default=DEFAULT_DB)
    parser.add_argument("--exclusions", type=Path, default=DEFAULT_EXCLUSIONS)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--searched-through",
        type=int,
        help="the last rank the builder has looked at; inferred from the"
        " database when not given",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the tracked file is out of date",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    setup_logging(args.verbose)

    species = load_species(args.species)
    ranks = plate_ranks(args.plates)
    through = args.searched_through or searched_through(ranks, species)
    report = build(species, ranks, refusals(args.exclusions), through)
    text = render(report)

    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            log.error(
                "%s is out of date; run python -m scripts.missing_plates", args.out
            )
            return 1
        log.info("%s is up to date", args.out)
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    counts = report["counts"]
    log.info(
        "%d of %d species have a plate; %d searched and empty, %d excluded,"
        " %d ranks not yet searched -> %s",
        counts["with_plate"],
        counts["species"],
        counts["searched_no_plate"],
        counts["excluded"],
        counts["not_yet_searched"],
        args.out,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
